// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp_2zBQsdv8fpHi5dLT-bRMftZHjgJe_w',
    appId: '1:220371487411:web:24b52045df37cb68613ec6',
    messagingSenderId: '220371487411',
    projectId: 'quadra-facil-app',
    authDomain: 'quadra-facil-app.firebaseapp.com',
    databaseURL: 'https://quadra-facil-app-default-rtdb.firebaseio.com',
    storageBucket: 'quadra-facil-app.firebasestorage.app',
    measurementId: 'G-7XW03PJ4GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyfBSwZcdA_NkOXOzzrE1V0X5Jam3IlA',
    appId: '1:220371487411:android:23179bb2f47a4d7b613ec6',
    messagingSenderId: '220371487411',
    projectId: 'quadra-facil-app',
    databaseURL: 'https://quadra-facil-app-default-rtdb.firebaseio.com',
    storageBucket: 'quadra-facil-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBEuH3axbbaIBfaXu1ZquGpqnvEXJ-8Kw',
    appId: '1:220371487411:ios:a914d14ef386a470613ec6',
    messagingSenderId: '220371487411',
    projectId: 'quadra-facil-app',
    databaseURL: 'https://quadra-facil-app-default-rtdb.firebaseio.com',
    storageBucket: 'quadra-facil-app.firebasestorage.app',
    iosBundleId: 'com.example.quadrafacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBEuH3axbbaIBfaXu1ZquGpqnvEXJ-8Kw',
    appId: '1:220371487411:ios:a914d14ef386a470613ec6',
    messagingSenderId: '220371487411',
    projectId: 'quadra-facil-app',
    databaseURL: 'https://quadra-facil-app-default-rtdb.firebaseio.com',
    storageBucket: 'quadra-facil-app.firebasestorage.app',
    iosBundleId: 'com.example.quadrafacil',
  );
}
